### PR TITLE
LLxD/issue31

### PR DESCRIPTION
**Pull request by LLxD**
## Motivation

Our client asked for a FAQ section, this is it, resolving #31  👍 

## Proposed solution

I developed a responsible FAQ section, with all of our clients questions and answers in them.

Desktop:
image
image

Mobile:
image
image

## Related Issues

Closing #31 if approved.

### CODE REVIEW

**Review by MarcosNBJ — APPROVED** [review]

**Review by MarcosNBJ — CHANGES_REQUESTED** [review]
The text got a little too big here. Maybe we could tone it down just to "É seguro comprar seguidores?". Also, it could be better centralized, it's too close to the bottom of the card. 

image

**Review by MarcosNBJ — CHANGES_REQUESTED** [review]
The animation for expanding the card can also be improved a little. Maybe making it slower. Right now it's too immediate.

**Comment by LLxD** [comment]
@MarcosNBJ, 

> The animation for expanding the card can also be improved a little. Maybe making it slower. Right now it's too immediate.
Fixed in 36cf652

> The animation for expanding the card can also be improved a little. Maybe making it slower. Right now it's too immediate.
Fixed and improved in c2095cc and 8a8c497

Requesting another review! 👍 

Deploy at: 

https://deploy-preview-39--impulsionaseguidores.netlify.app/

**Review by MarcosNBJ — APPROVED** [review]
Looks good now!

**Pull request merged**
